name: Release Addon

on:
  push:
    tags:
      - '**'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release Addon
        uses: BigWigsMods/packager@v2
